//! Currency symbol tables, extracted verbatim from the `price-parser` Python package
//! (PYTHONHASHSEED=0). Do not edit by hand.

/// Unambiguous currency symbols, matched anywhere; order matters ($-variants first).
pub(crate) static SAFE_CURRENCY_SYMBOLS: &[&str] = &[
    "Bds$",
    "CUC$",
    "MOP$",
    "AR$",
    "AU$",
    "BN$",
    "BZ$",
    "CA$",
    "CL$",
    "CO$",
    "CV$",
    "HK$",
    "MX$",
    "NT$",
    "NZ$",
    "TT$",
    "RD$",
    "WS$",
    "US$",
    "$U",
    "C$",
    "J$",
    "N$",
    "R$",
    "S$",
    "T$",
    "Z$",
    "A$",
    "SY£",
    "LB£",
    "CN¥",
    "GH₵",
    "$",
    "€",
    "£",
    "zł",
    "Zł",
    "Kč",
    "₽",
    "¥",
    "￥",
    "฿",
    "դր.",
    "դր",
    "₦",
    "₴",
    "₱",
    "৳",
    "₭",
    "₪",
    "﷼",
    "៛",
    "₩",
    "₫",
    "₡",
    "টকা",
    "ƒ",
    "₲",
    "؋",
    "₮",
    "नेरू",
    "₨",
    "₶",
    "₾",
    "֏",
    "ރ",
    "৲",
    "૱",
    "௹",
    "₠",
    "₢",
    "₣",
    "₤",
    "₧",
    "₯",
    "₰",
    "₳",
    "₷",
    "₸",
    "₹",
    "₺",
    "₼",
    "₾",
    "₿",
    "ℳ",
    "ر.ق.‏",
    "د.ك.‏",
    "د.ع.‏",
    "ر.ع.‏",
    "ر.ي.‏",
    "ر.س.‏",
    "د.ج.‏",
    "د.م.‏",
    "د.إ.‏",
    "د.ت.‏",
    "د.ل.‏",
    "ل.س.‏",
    "د.ب.‏",
    "د.أ.‏",
    "ج.م.‏",
    "ل.ل.‏",
    " تومان",
    "تومان",
    "درهم",
    "ريال",
    "جنيه",
    "EUR",
    "euro",
    "eur",
    "CHF",
    "DKK",
    "Rp",
    "lei",
    "руб.",
    "руб",
    "грн.",
    "грн",
    "дин.",
    "Dinara",
    "динар",
    "лв.",
    "лв",
    "р.",
    "тңг",
    "тңг.",
    "ман.",
];

/// Less-safe currency symbols/codes, sorted longest-first.
pub(crate) static OTHER_CURRENCY_SYMBOLS: &[&str] = &[
    "tolarjev", "D-Mark", "SL Re", "Bs.F.", "Sucre", "kroon", "man.", "NPRs", "Ptas", "FCFA",
    "Δρχ.", "ریال", "din.", "Afl.", "litų", "FrCD", "SLRs", "MURs", "PKRs", "GIP", "BOV", "LRD",
    "NLG", "XPT", "CLP", "EEK", "B/.", "IQD", "XBA", "TWD", "VEF", "DOP", "UGX", "LUF", "FJD",
    "BAM", "pln", "VND", "EGP", "SSP", "UYU", "KRW", "BOB", "USN", "GBP", "LSL", "JPY", "BEF",
    "GGP", "Skr", "BIF", "RSD", "OMR", "NAD", "KZT", "SOS", "VUV", "S/.", "Lek", "IEP", "MRf",
    "KGS", "RON", "CFA", "Fdj", "TVD", "SLL", "KMF", "BGN", "Pts", "ZWD", "MXN", "HNL", "ZMW",
    "LTL", "CLF", "ZWL", "IRR", "ISK", "JMD", "CRC", "Nkr", "RUB", "Ssh", "JOD", "ETB", "CDF",
    "MZN", "BMD", "BWP", "NZD", "ERN", "leu", "MWK", "Ikr", "Nu.", "XDR", "VAL", "LYD", "KWD",
    "TTD", "PGK", "FBu", "XAG", "AZN", "NGN", "ANG", "TZS", "MVR", "CUP", "SEK", "AED", "USh",
    "MNT", "SGD", "LAK", "SDG", "SCR", "XAU", "THB", "XBC", "COP", "MAD", "FIM", "NPR", "XBB",
    "MTL", "CHW", "Lei", "GHS", "SKK", "PYG", "RMB", "Fr.", "XOF", "BZD", "IDR", "UYI", "Ksh",
    "XUA", "KPW", "USD", "XPD", "GYD", "HUF", "GTQ", "MGA", "KYD", "INR", "XAF", "ALL", "LKR",
    "XSU", "Pta", "AOA", "SAR", "PKR", "XBD", "KES", "SZL", "SVC", "AFL", "MMK", "QAR", "TRY",
    "PLN", "CZK", "TND", "GRD", "BYN", "WST", "BTN", "PHP", "IR£", "PAB", "SIT", "COU", "IMP",
    "MXV", "AWG", "PRB", "SYP", "DEM", "ZMK", "XPF", "AMD", "CYP", "PEN", "TOP", "NTD", "FRF",
    "SBD", "LVL", "JEP", "XTS", "CFP", "MKD", "MRO", "RWF", "ILS", "BBD", "CVE", "NIO", "STD",
    "CHE", "Dkr", "GMD", "FKP", "ESP", "CAD", "MUR", "NOK", "UZS", "MTn", "CUC", "MYR", "fl.",
    "Nfk", "PTE", "MOP", "DZD", "LBP", "CNY", "DJF", "SRD", "AUD", "TMT", "Δρ.", "GNF", "UAH",
    "BRL", "AFN", "HKD", "BHD", "mk.", "YER", "fr.", "ARS", "SHP", "KHR", "ITL", "HRK", "BDT",
    "BSD", "ATS", "LEI", "ZAR", "TSh", "HTG", "MDL", "TJS", "BND", "GEL", "XCD", "Le", "FG", "KM",
    "Rf", "FC", "kn", "DA", "DM", "KD", "YR", "TL", "Bs", "SR", "öS", "UF", "Lm", "Rs", "UM", "Tk",
    "QR", "MK", "Br", "DT", "LD", "ZK", "Sk", "RM", "BD", "FR", "VT", "Ls", "Kz", "Db", "JD", "Pt",
    "CF", "Af", "Ft", "Lt", "kr", "р", "원", "円", "र", "đ", "Р",
];

/// Currency codes ending in `D` that take priority over a `$` sign.
pub(crate) static DOLLAR_CODES: &[&str] = &[
    "AED", "AMD", "AUD", "BBD", "BHD", "BSD", "BMD", "BND", "BZD", "CAD", "DZD", "FJD", "GMD",
    "GYD", "HKD", "IQD", "JMD", "JOD", "KWD", "KYD", "LRD", "LYD", "MAD", "MKD", "NAD", "NZD",
    "RSD", "SBD", "SGD", "SRD", "STD", "TND", "TTD", "TVD", "TWD", "USD", "VND", "XBD", "XCD",
    "XPD", "ZWD", "NTD", "GRD",
];
